name: XcloudTest
options:
  indentWidth: 2
  tabWidth: 2
targets:
  XcloudTest:
    type: application
    platform: iOS
    deploymentTarget: 15.5
    sources: [XcloudTest]
    scheme:
      testTargets:
        - XcloudTestTests
      gatherCoverageData: true
      coverageTargets:
        - XcloudTest
      commandLineArguments:
        "-FIRAnalyticsDebugEnabled": false
    settings:
      base:
        MARKETING_VERSION: 1.0.0 # Version Number
        CURRENT_PROJECT_VERSION: 1.0 # Build Number
        OTHER_LDFLAGS: -Xlinker -interposable
      postCompileScripts:
        - script: >-
            if which swiftlint >/dev/null; then
              swiftlint
            else
              echo "warning: swiftlint not installed."
            fi

          name: SwiftLint
        
  XcloudTestTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: XcloudTestTests
